# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/opensearch.dremio.io_opensearchactiongroups.yaml
- bases/opensearch.dremio.io_opensearchclusters.yaml
- bases/opensearch.dremio.io_opensearchcomponenttemplates.yaml
- bases/opensearch.dremio.io_opensearchindextemplates.yaml
- bases/opensearch.dremio.io_opensearchroles.yaml
- bases/opensearch.dremio.io_opensearchtenants.yaml
- bases/opensearch.dremio.io_opensearchuserrolebindings.yaml
- bases/opensearch.dremio.io_opensearchusers.yaml
- bases/opensearch.dremio.io_opensearchismpolicies.yaml
- bases/crd-servicemonitor.yaml
- bases/opensearch.dremio.io_opensearchsnapshotpolicies.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_opensearch.yaml
#- path: patches/webhook_in_opensearchusers.yaml
#- path: patches/webhook_in_opensearchroles.yaml
#- path: patches/webhook_in_opensearchuserrolebindings.yaml
#- path: patches/webhook_in_opensearchtenants.yaml
#- path: patches/webhook_in_opensearchactiongroups.yaml
#- path: patches/webhook_in_opensearchismpolicies.yaml
#- path: patches/webhook_in_opensearchsnapshotpolicies.yaml
#- path: patches/webhook_in_opensearchindextemplates.yaml
#- path: patches/webhook_in_opensearchcomponenttemplates.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- path: patches/cainjection_in_opensearch.yaml
- path: patches/cainjection_in_opensearchusers.yaml
- path: patches/cainjection_in_opensearchroles.yaml
- path: patches/cainjection_in_opensearchuserrolebindings.yaml
- path: patches/cainjection_in_opensearchtenants.yaml
- path: patches/cainjection_in_opensearchactiongroups.yaml
- path: patches/cainjection_in_opensearchismpolicies.yaml
- path: patches/cainjection_in_opensearchsnapshotpolicies.yaml
- path: patches/cainjection_in_opensearchindextemplates.yaml
- path: patches/cainjection_in_opensearchcomponenttemplates.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
